### ISSUE TITLE
how to load pmx?

### ISSUE THREAD

**Issue by mtsee** [takahirox/MMDLoader-app#2]
this just load .pmd file, how to load .pmx file ？thanks

**Comment by takahirox** [comment]
Juse use `.load` or `.loadModel` method. They support both `.pmd` and `.pmx`.

**Comment by mtsee** [comment]
MMDLoader.js:809 Uncaught TypeError: Cannot read property 'type' of undefined
    at initMorphs (MMDLoader.js:809)
    at THREE.MMDLoader.createMesh (MMDLoader.js:1493)
    at THREE.MMDLoader.createModel (MMDLoader.js:117)
    at MMDLoader.js:109
    at MMDLoader.js:463
    at XMLHttpRequest.<anonymous> (three.js:30090)

this type is not

**Comment by takahirox** [comment]
Using the latest `MMDLoader` in Three.js repo?

**Comment by mtsee** [comment]
I will try to download the latest version. thx

**Comment by takahirox** [comment]
Share your `.pmx` file with me if the error still shows up with the latest version. I can look into.

**Comment by takahirox** [comment]
Please reopen if you still face the problem
